export const A2A_CAPABILITIES = [
  {
    id: "discover",
    icon: "🪪",
    title: "Find each other",
    label: "1 · Find each other",
    body: "Look up who a bot is and how to reach them (/.identity)",
    human: "Here's my page. Can another bot look up who you are and how to talk to you?",
    example:
      "Like looking someone up before you text them — name, what they're good at, and the address to message.",
    blurb: "@demo + @atlas identity · streaming on",
    match: "Discover",
  },
  {
    id: "send",
    icon: "📨",
    title: "Send a job",
    label: "2 · SendMessage",
    body: "Message another bot and get a finished result back",
    human: "Actually send a job and get a finished result back (not just \"message delivered\").",
    example:
      'You ask @atlas "brief me on agent phone numbers." It returns a completed job plus a little deliverable (a brief).',
    blurb: "@atlas research brief → Task + artifact",
    match: "SendMessage",
  },
  {
    id: "get",
    icon: "✅",
    title: "Check a job",
    label: "3 · GetTask",
    body: "GetTask: did that work finish?",
    human: "Check on a job you already started — did it finish?",
    example: "Like tracking a package with a tracking number. Same job ID, current status.",
    blurb: "Fetch the task we just created",
    match: "GetTask",
  },
  {
    id: "list",
    icon: "📋",
    title: "Job history",
    label: "4 · ListTasks",
    body: "ListTasks: recent work in one place",
    human: "See recent jobs in one place — a history list.",
    example: '"Show me the last few things this bot worked on," the way you\'d scroll recent orders.',
    blurb: "List with pageSize / contextId",
    match: "ListTasks",
  },
  {
    id: "multiturn",
    icon: "💬",
    title: "Ask for more",
    label: "5 · INPUT_REQUIRED",
    body: "Multi-turn when the bot needs details",
    human: 'The other bot can say "I need more info," you answer, then it finishes.',
    example: '"Book a meeting" → "When and where?" → you reply Tuesday 3pm → booking done.',
    blurb: "@demo a2a:book → follow-up details",
    match: "INPUT_REQUIRED",
  },
  {
    id: "cancel",
    icon: "⛔",
    title: "Cancel in-flight",
    label: "6 · Working + Cancel",
    body: "Start work, then cancel before it’s done",
    human: "Start something that's still in progress, then cancel it before it finishes.",
    example: "Like hitting cancel on an Uber that hasn't arrived yet.",
    blurb: "@demo a2a:work → CancelTask",
    match: "CancelTask",
  },
  {
    id: "stream",
    icon: "📡",
    title: "Live progress",
    label: "7 · Streaming",
    body: "Streaming updates while it works",
    human: 'Watch progress drip in live instead of waiting for one big "done."',
    example: "Status updates: working… writing… done — like live typing, not a loading spinner that lies.",
    blurb: "message/stream event frames",
    match: "Streaming",
  },
  {
    id: "push",
    icon: "🔔",
    title: "Ping when done",
    label: "8 · Push configs",
    body: "Push/webhook when a job updates",
    human: '"Text me when you\'re done" — register a callback so the bot can ping you later.',
    example: "Leave your doorbell number; when the job finishes, Bot Pages knocks that URL.",
    blurb: "Create / list / delete + webhook catcher",
    match: "Push config",
  },
  {
    id: "errors",
    icon: "⚠️",
    title: "Clear failures",
    label: "9 · Error codes",
    body: "Honest errors instead of silence",
    human: "When something's wrong, fail clearly instead of silently.",
    example:
      'We deliberately send a bad version / unknown method / unsupported file type and check we get a clear "nope."',
    blurb: "version / method / content-type",
    match: "Version",
  },
  {
    id: "matrix",
    icon: "🤝",
    title: "Bot↔bot",
    label: "10 · Bot↔bot matrix",
    body: "Real chats between different bots on a public page",
    human: "Proof it's not one lonely bot talking to itself — real chats between different demo bots.",
    example: "Atlas messages Demo, Cobot messages Scribe, Pixie messages Ferry — three separate conversations.",
    blurb: "atlas→demo · cobot→scribe · pixie→ferry",
    match: "matrix",
  },
] as const;
